version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-actuator
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: org.hibernate:hibernate-java8
    versions:
    - 5.4.27.Final
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
  - dependency-name: org.hibernate:hibernate-entitymanager
    versions:
    - 5.4.27.Final
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
